USE Chinook

--TOP 10 TOTAL DE VENDAS POR GÊNERO MUSICAL
SELECT TOP 10
G.Name AS GÊNERO,
	SUM(I.LineTotal) AS TOTAL_VENDAS
FROM InvoiceLine AS I
INNER JOIN Track AS T ON T.TrackId = I.TrackId
INNER JOIN Genre AS G ON G.GenreId = T.GenreId
GROUP BY G.Name
ORDER BY TOTAL_VENDAS DESC

--TOP 10 TOTAL DE VENDAS POR ARTISTAS
SELECT TOP 10
AR.Name AS ARTISTA,
	SUM(I.LineTotal) AS TOTAL_VENDAS
FROM InvoiceLine AS I
INNER JOIN Track AS T ON T.TrackId = I.TrackId
INNER JOIN Album AS A ON A.AlbumId = T.AlbumId
INNER JOIN Artist AS AR ON AR.ArtistId = A.ArtistId
GROUP BY AR.Name
ORDER BY TOTAL_VENDAS DESC

--TOP 10 TOTAL DE VENDAS POR MÚSICA
SELECT TOP 10
	T.Name AS MÚSICA,
	SUM(I.LineTotal) AS TOTAL_VENDAS,
	SUM(I.Quantity) AS QUANTIDADE
FROM InvoiceLine AS I
INNER JOIN Track AS T ON T.TrackId = I.TrackId
INNER JOIN ALBUM AS A ON A.AlbumId = T.AlbumId
INNER JOIN Artist AS AR ON AR.ArtistId = A.ArtistId
GROUP BY T.Name
ORDER BY TOTAL_VENDAS DESC

--TOTAL DE VENDAS POR MÊS NO PERÍODO TOTAL
SELECT 
	MONTH(I.Invoicedate) MÊS,
	SUM(I.InvoiceTotal) AS TOTAL_VENDAS
FROM Invoice AS I
GROUP BY  MONTH(I.Invoicedate)
ORDER BY MÊS DESC



